package net.yackrond.dndmod.item;

import net.minecraft.core.registries.Registries;
import net.minecraft.network.chat.Component;
import net.minecraft.world.item.CreativeModeTab;
import net.minecraft.world.item.ItemStack;
import net.minecraftforge.eventbus.api.IEventBus;
import net.minecraftforge.registries.DeferredRegister;
import net.minecraftforge.registries.RegistryObject;
import net.yackrond.dndmod.DnDMod;
import net.yackrond.dndmod.block.ModBlocks;

public class ModCreativeModeTabs {
    public static final DeferredRegister<CreativeModeTab> CREATIVE_MODE_TABS = DeferredRegister.create(Registries.CREATIVE_MODE_TAB, DnDMod.MOD_ID);

    public static final RegistryObject<CreativeModeTab> DND_TAB = CREATIVE_MODE_TABS.register("dnd_tab",
            () -> CreativeModeTab.builder().icon(() -> new ItemStack(ModItems.SILVER_INGOT.get()))
                    .title(Component.translatable("creativetab.dnd_tab")).displayItems((pParameters, pOutput) -> {
                        pOutput.accept(ModItems.SILVER_INGOT.get());
                        pOutput.accept(ModItems.SILVER_NUGGET.get());
                        pOutput.accept(ModItems.RAW_SILVER.get());
                        pOutput.accept(ModItems.METAL_DETECTOR.get());

                        pOutput.accept(ModBlocks.SILVER_ORE.get());
                        pOutput.accept(ModBlocks.SILVER_BLOCK.get());
                        pOutput.accept(ModBlocks.RAW_SILVER_BLOCK.get());
                        pOutput.accept(ModBlocks.DEEPSLATE_SILVER_ORE.get());
                        pOutput.accept(ModBlocks.NETHER_SILVER_ORE.get());
                        pOutput.accept(ModBlocks.END_SILVER_ORE.get());

                        pOutput.accept(ModBlocks.PLATINUM_ORE.get());
                        pOutput.accept(ModBlocks.PLATINUM_BLOCK.get());
                        pOutput.accept(ModBlocks.RAW_PLATINUM_BLOCK.get());
                        pOutput.accept(ModBlocks.DEEPSLATE_PLATINUM_ORE.get());
                        pOutput.accept(ModBlocks.NETHER_PLATINUM_ORE.get());
                        pOutput.accept(ModBlocks.END_PLATINUM_ORE.get());

                        pOutput.accept(ModBlocks.ADAMANT_ORE.get());
                        pOutput.accept(ModBlocks.ADAMANT_BLOCK.get());
                        pOutput.accept(ModBlocks.RAW_ADAMANT_BLOCK.get());
                        pOutput.accept(ModBlocks.DEEPSLATE_ADAMANT_ORE.get());
                        pOutput.accept(ModBlocks.NETHER_ADAMANT_ORE.get());
                        pOutput.accept(ModBlocks.END_ADAMANT_ORE.get());

                        pOutput.accept(ModBlocks.RUBY_ORE.get());
                        pOutput.accept(ModBlocks.RUBY_BLOCK.get());
                        pOutput.accept(ModBlocks.DEEPSLATE_RUBY_ORE.get());
                        pOutput.accept(ModBlocks.NETHER_RUBY_ORE.get());
                        pOutput.accept(ModBlocks.END_RUBY_ORE.get());

                        pOutput.accept(ModBlocks.SAPPHIRE_ORE.get());
                        pOutput.accept(ModBlocks.SAPPHIRE_BLOCK.get());
                        pOutput.accept(ModBlocks.DEEPSLATE_SAPPHIRE_ORE.get());
                        pOutput.accept(ModBlocks.NETHER_SAPPHIRE_ORE.get());
                        pOutput.accept(ModBlocks.END_SAPPHIRE_ORE.get());

                        pOutput.accept(ModBlocks.CHRYSOLITE_ORE.get());
                        pOutput.accept(ModBlocks.CHRYSOLITE_BLOCK.get());
                        pOutput.accept(ModBlocks.DEEPSLATE_CHRYSOLITE_ORE.get());
                        pOutput.accept(ModBlocks.NETHER_CHRYSOLITE_ORE.get());
                        pOutput.accept(ModBlocks.END_CHRYSOLITE_ORE.get());

                        pOutput.accept(ModBlocks.SUNSTONE_ORE.get());
                        pOutput.accept(ModBlocks.SUNSTONE_BLOCK.get());
                        pOutput.accept(ModBlocks.DEEPSLATE_SUNSTONE_ORE.get());
                        pOutput.accept(ModBlocks.NETHER_SUNSTONE_ORE.get());
                        pOutput.accept(ModBlocks.END_SUNSTONE_ORE.get());

                        pOutput.accept(ModBlocks.SOUND_BLOCK.get());
                        pOutput.accept(ModBlocks.SILVER_WALL.get());
                        pOutput.accept(ModBlocks.MACERATOR.get());
                    }).build());
    public static final RegistryObject<CreativeModeTab> SPELL_COMPONENTS_TAB = CREATIVE_MODE_TABS.register("spell_components_tab",
            () -> CreativeModeTab.builder().icon(() -> new ItemStack(ModItems.MINIATURE_CLOAK.get()))
            .title(Component.translatable("creativetab.spell_components_tab")).displayItems((pParameters, pOutput) -> {
                pOutput.accept(ModItems.MINIATURE_CLOAK.get());
                pOutput.accept(ModItems.MINIATURE_BELL.get());
                pOutput.accept(ModItems.SILVER_WIRE.get());
                pOutput.accept(ModItems.CURED_LEATHER.get());
                pOutput.accept(ModItems.HOLY_WATER_BOTTLE.get());
                pOutput.accept(ModItems.SILVER_MIRROR.get());
                pOutput.accept(ModItems.HOLY_TEXT.get());
                pOutput.accept(ModItems.ROPE.get());
                pOutput.accept(ModItems.CLOTH.get());
                pOutput.accept(ModItems.CLOTH_STRIP.get());
                pOutput.accept(ModItems.MISTLETOE_ASHES.get());
                pOutput.accept(ModItems.LINKED_PLATINUM_RINGS.get());
                pOutput.accept(ModItems.INCENSE.get());
                pOutput.accept(ModItems.LEATHER_STRAP.get());
                pOutput.accept(ModItems.BROKEN_PORTAL_KEY.get());
                pOutput.accept(ModItems.LEAD_SHEET.get());
                pOutput.accept(ModItems.COTTON.get());
                pOutput.accept(ModItems.GOLD_TINGED_FULL_MOON_MISTLETOE.get());
                pOutput.accept(ModItems.PLATINUM_PLATED_DRAGON_SCALE.get());
                pOutput.accept(ModItems.RARE_INCENSE.get());
                pOutput.accept(ModItems.GLASS_ORB.get());
                pOutput.accept(ModItems.AMETHYST_ORB.get());
                pOutput.accept(ModItems.BURNING_INCENSE.get());
                pOutput.accept(ModItems.VIAL_OF_BRIMSTONE_AND_PITCH.get());
                pOutput.accept(ModItems.VIAL_OF_UMBER_HULK_BLOOD.get());
                pOutput.accept(ModItems.SILVER_ROD.get());
                pOutput.accept(ModItems.QUICKSILVER_BOTTLE.get());
                pOutput.accept(ModItems.PHOSPHORUS.get());
                pOutput.accept(ModItems.OPAL.get());
                pOutput.accept(ModItems.MITHRIL_ORB.get());
                pOutput.accept(ModItems.MINIATURE_JADE_PRISON.get());
                pOutput.accept(ModItems.SOPORIFIC_HERBS.get());
                pOutput.accept(ModItems.ADAMANTINE_INGOT.get());
                pOutput.accept(ModItems.FLEA_IN_BOTTLE.get());
                pOutput.accept(ModItems.MIXED_HERBS.get());
                pOutput.accept(ModItems.BRASS_BRAZIER.get());
                pOutput.accept(ModItems.TALLOW.get());
                pOutput.accept(ModItems.BUTTER.get());
                pOutput.accept(ModItems.VIAL_OF_WATER.get());
                pOutput.accept(ModItems.VIAL_OF_QUICKSILVER.get());
                pOutput.accept(ModItems.GLASS_SHARD.get());
                pOutput.accept(ModItems.DUST.get());
                pOutput.accept(ModItems.BRIMSTONE.get());
                pOutput.accept(ModItems.DECK_OF_CARDS.get());
                pOutput.accept(ModItems.FOX_FUR.get());
                pOutput.accept(ModItems.FISH_TAIL.get());
                pOutput.accept(ModItems.GILDED_ACORN.get());
                pOutput.accept(ModItems.PICKLED_TENTACLE.get());
                pOutput.accept(ModItems.TENTACLE.get());
                pOutput.accept(ModItems.HOLY_SYMBOL.get());
                pOutput.accept(ModItems.ROTTEN_EGG.get());
                pOutput.accept(ModItems.SKUNK_CABBAGE.get());
                pOutput.accept(ModItems.GILDED_FLOWER.get());
                pOutput.accept(ModItems.VIAL_OF_FRESH_BLOOD.get());
                pOutput.accept(ModItems.VIAL_OF_BLOOD.get());
                pOutput.accept(ModItems.AMETHYST_VIAL_OF_TEARS.get());
                pOutput.accept(ModItems.SILVER_WHISTLE.get());
                pOutput.accept(ModItems.PLATINUM_VIAL_OF_EYEBALL.get());
                pOutput.accept(ModItems.ORNATE_STONE.get());
                pOutput.accept(ModItems.PEBBLE.get());
                pOutput.accept(ModItems.ASH.get());
                pOutput.accept(ModItems.GOLD_VIAL.get());
                pOutput.accept(ModItems.GRAIN.get());
                pOutput.accept(ModItems.RELIQUARY.get());
                pOutput.accept(ModItems.DRAGON_INSIGNIA.get());
                pOutput.accept(ModItems.RUBY_VIAL_OF_FRESH_BLOOD.get());
                pOutput.accept(ModItems.RUBY_VIAL_OF_BLOOD.get());
                pOutput.accept(ModItems.THORNY_TWIG.get());
                pOutput.accept(ModItems.MINIATURE_IVORY_PORTAL.get());
                pOutput.accept(ModItems.SILVER_SPOON.get());
                pOutput.accept(ModItems.OVERWORLD_ATTUNED_TUNING_FORK.get());
                pOutput.accept(ModItems.NETHER_ATTUNED_TUNING_FORK.get());
                pOutput.accept(ModItems.END_ATTUNED_TUNING_FORK.get());
                pOutput.accept(ModItems.CLOTH_WRAPPED_FUR.get());
                pOutput.accept(ModItems.SALT.get());
                pOutput.accept(ModItems.PEARL.get());
                pOutput.accept(ModItems.OWL_FEATHER.get());
                pOutput.accept(ModItems.MARKED_STICK.get());
                pOutput.accept(ModItems.MARKED_BONE.get());
                pOutput.accept(ModItems.COPPER_PIECE.get());
                pOutput.accept(ModItems.BLOODHOUND_FUR.get());
                pOutput.accept(ModItems.TUNING_FORK.get());
                pOutput.accept(ModItems.TALC.get());
                pOutput.accept(ModItems.GLASS_EYE.get());
                pOutput.accept(ModItems.MINIATURE_CLAY_ZIGGURAT.get());
                pOutput.accept(ModItems.BAT_FUR.get());
                pOutput.accept(ModItems.VIAL_OF_HOLY_WATER.get());
                pOutput.accept(ModItems.VIAL_OF_UNHOLY_WATER.get());
                pOutput.accept(ModItems.IVORY_STRIP.get());
                pOutput.accept(ModItems.FOCUS.get());
                pOutput.accept(ModItems.VIAL_OF_EYE_OINTMENT.get());
                pOutput.accept(ModItems.HUMMINGBIRD_FEATHER.get());
                pOutput.accept(ModItems.PETRIFIED_NEWT_EYE.get());
                pOutput.accept(ModItems.ROSE_PETAL.get());
                pOutput.accept(ModItems.CRICKET_IN_BOTTLE.get());
                pOutput.accept(ModItems.TINY_TART.get());
                pOutput.accept(ModItems.SILVER_PIECE.get());
                pOutput.accept(ModItems.GOLD_PIECE.get());
                pOutput.accept(ModItems.PLATINUM_PIECE.get());
                pOutput.accept(ModItems.SNAKE_TONGUE.get());
                pOutput.accept(ModItems.VIAL_OF_SWEET_OIL.get());
                pOutput.accept(ModItems.ACORN.get());
                pOutput.accept(ModItems.VINEGAR_SOAKED_SALT.get());
                pOutput.accept(ModItems.VIAL_OF_HONEY.get());
                pOutput.accept(ModItems.CLAY_ORB.get());
                pOutput.accept(ModItems.DIAMOND_ORB.get());
                pOutput.accept(ModItems.EMERALD_ORB.get());
                pOutput.accept(ModItems.RUBY_ORB.get());
                pOutput.accept(ModItems.SAPPHIRE_ORB.get());
                pOutput.accept(ModItems.GLOWWORM_IN_BOTTLE.get());
                pOutput.accept(ModItems.FIREFLY_IN_BOTTLE.get());
                pOutput.accept(ModItems.PHOSPHORESCENT_MOSS.get());
                pOutput.accept(ModItems.FULGUROUS_TWIG.get());
                pOutput.accept(ModItems.RED_DRAGON_SCALE.get());
                pOutput.accept(ModItems.VIAL_OF_PITCH.get());
                pOutput.accept(ModItems.SUMAC_BERRY.get());
                pOutput.accept(ModItems.PEANUT.get());
                pOutput.accept(ModItems.POWDERED_RHUBARB.get());
                pOutput.accept(ModItems.SNAKE_STOMACH.get());
                pOutput.accept(ModItems.MOONSEED_SEEDS.get());
                pOutput.accept(ModItems.OPALESCENT_FELDSPAR_CHUNK.get());
                pOutput.accept(ModItems.FLAMMABLE_ORB.get());
                pOutput.accept(ModItems.AMBER_ROD.get());
                pOutput.accept(ModItems.AMETHYST_ROD.get());
                pOutput.accept(ModItems.GLASS_ROD.get());
                pOutput.accept(ModItems.EXPLOSIVE_ORB.get());
                pOutput.accept(ModItems.COPPER_WIRE.get());
                pOutput.accept(ModItems.PAPER_FAN.get());
                pOutput.accept(ModItems.BLACK_PEARL.get());
                pOutput.accept(ModItems.GLASS_HALF_ORB.get());
                pOutput.accept(ModItems.GUM_ARABIC_HALF_ORB.get());
                pOutput.accept(ModItems.VIAL_OF_SLUG_BILE.get());
                pOutput.accept(ModItems.SNAKESKIN_GLOVE.get());
                pOutput.accept(ModItems.AMETHYST_CONE.get());
                pOutput.accept(ModItems.GLASS_CONE.get());
                pOutput.accept(ModItems.SUNBURST_PENDANT.get());
                pOutput.accept(ModItems.PAPER_CONE.get());
                pOutput.accept(ModItems.LEAF_CONE.get());
                pOutput.accept(ModItems.SILVER_PIN.get());
                pOutput.accept(ModItems.MAGNIFYING_GLASS.get());
                pOutput.accept(ModItems.ORNAMENTAL_SWORD.get());
                pOutput.accept(ModItems.ONYX.get());
                pOutput.accept(ModItems.VIAL_OF_PITCH_AND_QUICKSILVER.get());
                pOutput.accept(ModItems.LINKED_SILVER_RINGS.get());
                pOutput.accept(ModItems.IRON_STAR.get());
                pOutput.accept(ModItems.LEAD_BASED_INK_BOTTLE.get());
                pOutput.accept(ModItems.EYELASH_IN_GUM_ARABIC.get());
                pOutput.accept(ModItems.POWDERED_JADE.get());
                pOutput.accept(ModItems.APPLE_PIE_CRUST.get());
                pOutput.accept(ModItems.SILK.get());
                pOutput.accept(ModItems.CHICKEN_HEART.get());
                pOutput.accept(ModItems.SOPORIFIC_QUILL.get());
                pOutput.accept(ModItems.MINIATURE_PLAYER.get());
                pOutput.accept(ModItems.UNDEAD_EYE_IN_DIAMOND.get());
                pOutput.accept(ModItems.BROKEN_BONE.get());
                pOutput.accept(ModItems.BLACK_SILK.get());
                pOutput.accept(ModItems.POWDERED_BLACK_PEARL.get());
                pOutput.accept(ModItems.POT_OF_GRAVE_DIRT.get());
                pOutput.accept(ModItems.POT_OF_BRACKISH_WATER.get());
                pOutput.accept(ModItems.MINIATURE_SILVER_CAGE.get());
                pOutput.accept(ModItems.PLATINUM_WIRE.get());
                pOutput.accept(ModItems.ORNATE_SILVER_INGOT.get());
                pOutput.accept(ModItems.DIAMANTINE_HOURGLASS.get());
                pOutput.accept(ModItems.MISTLETOE.get());
                pOutput.accept(ModItems.SHAMROCK.get());
                pOutput.accept(ModItems.DRIED_CARROT.get());
                pOutput.accept(ModItems.HOT_PEPPER.get());
                pOutput.accept(ModItems.GOLD_HOOK.get());
                pOutput.accept(ModItems.MINIATURE_CLAY_HAND.get());
                pOutput.accept(ModItems.POWDERED_CORN.get());
                pOutput.accept(ModItems.TWISTED_PAPER.get());
                pOutput.accept(ModItems.SPIDER_IN_BOTTLE.get());
                pOutput.accept(ModItems.SMOKE_IN_BOTTLE.get());
                pOutput.accept(ModItems.LIQUORICE_ROOT.get());
                pOutput.accept(ModItems.VIAL_OF_MOLASSES.get());
                pOutput.accept(ModItems.CORK.get());
                pOutput.accept(ModItems.COCOON.get());
                pOutput.accept(ModItems.SESAME_SEEDS.get());
                pOutput.accept(ModItems.QUIVER.get());
                pOutput.accept(ModItems.MANDRAKE_ROOT.get());
                pOutput.accept(ModItems.IRON_BLADE.get());
                pOutput.accept(ModItems.BAG_OF_SOILS.get());
                pOutput.accept(ModItems.OUTER_PLANES_INSIGNIA.get());
                pOutput.accept(ModItems.ORNATE_AMETHYST_ROD.get());
                pOutput.accept(ModItems.PRAYER_WHEEL.get());
                pOutput.accept(ModItems.POT_OF_DEBRIS.get());
                pOutput.accept(ModItems.JADE_CIRCLET.get());
                pOutput.accept(ModItems.GUM_ARABIC.get());
                pOutput.accept(ModItems.MITHRIL_CHAIN.get());
                pOutput.accept(ModItems.GOLD_CHAIN.get());
                pOutput.accept(ModItems.SILVER_CHAIN.get());
                pOutput.accept(ModItems.PLATINUM_CHAIN.get());
                pOutput.accept(ModItems.ADAMANT_CHAIN.get());
                pOutput.accept(ModItems.OIL_BOTTLE.get());
                pOutput.accept(ModItems.VELLUM.get());
                pOutput.accept(ModItems.MINIATURE_ORNATE_CHEST.get());
                pOutput.accept(ModItems.GEM_INFUSED_CHALK.get());
                pOutput.accept(ModItems.GEM_INFUSED_INK.get());
                pOutput.accept(ModItems.LOCKBOX.get());
                pOutput.accept(ModItems.GEM_ENCRUSTED_BOWL.get());
                pOutput.accept(ModItems.AMETHYST_PRISM.get());
                pOutput.accept(ModItems.DIAMOND_PRISM.get());
                pOutput.accept(ModItems.EMERALD_PRISM.get());
                pOutput.accept(ModItems.RUBY_PRISM.get());
                pOutput.accept(ModItems.SAPPHIRE_PRISM.get());
                pOutput.accept(ModItems.GEM_ENCRUSTED_HORN.get());
                pOutput.accept(ModItems.OWL_EGG.get());
                pOutput.accept(ModItems.HUMMINGBIRD_EGG.get());
            }).build());
    public static void register(IEventBus eventBus) {
        CREATIVE_MODE_TABS.register(eventBus);
    }
}
